import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    email: v.string(),
    passwordHash: v.string(),
    name: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_email", ["email"]),
  locationRatings: defineTable({
    locationId: v.string(),
    sessionId: v.string(),
    rating: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_location_session", ["locationId", "sessionId"]),
  ratingSummaries: defineTable({
    locationId: v.string(),
    ratingCount: v.number(),
    ratingSum: v.number(),
    updatedAt: v.number(),
  }).index("by_locationId", ["locationId"]),
  userRatings: defineTable({
    locationId: v.string(),
    userId: v.id("users"),
    rating: v.number(),
    comment: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_location_user", ["locationId", "userId"]).index("by_location", ["locationId"]).index("by_user", ["userId"]),
  userFavorites: defineTable({
    locationId: v.string(),
    userId: v.id("users"),
    createdAt: v.number(),
  }).index("by_location_user", ["locationId", "userId"]).index("by_user", ["userId"]),
  friendRequests: defineTable({
    senderId: v.id("users"),
    receiverId: v.id("users"),
    senderEmail: v.string(),
    receiverEmail: v.string(),
    status: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_receiver_status", ["receiverId", "status"]).index("by_sender_status", ["senderId", "status"]).index("by_pair", ["senderId", "receiverId"]),
  friendships: defineTable({
    userId: v.id("users"),
    friendUserId: v.id("users"),
    createdAt: v.number(),
  }).index("by_user_friend", ["userId", "friendUserId"]).index("by_user", ["userId"]),
  curatedLocations: defineTable({
    id: v.string(),
    name: v.string(),
    type: v.string(),
    types: v.optional(v.array(v.string())),
    lat: v.number(),
    lng: v.number(),
    mediaType: v.string(),
    mediaURL: v.string(),
    thumbnailUrl: v.optional(v.string()),
    externalUrl: v.optional(v.string()),
    googleMapsUrl: v.optional(v.string()),
    tags: v.array(v.string()),
    detailedTags: v.optional(v.array(v.string())),
    hours: v.optional(v.object({
      monday: v.optional(v.object({ open: v.string(), close: v.string() })),
      tuesday: v.optional(v.object({ open: v.string(), close: v.string() })),
      wednesday: v.optional(v.object({ open: v.string(), close: v.string() })),
      thursday: v.optional(v.object({ open: v.string(), close: v.string() })),
      friday: v.optional(v.object({ open: v.string(), close: v.string() })),
      saturday: v.optional(v.object({ open: v.string(), close: v.string() })),
      sunday: v.optional(v.object({ open: v.string(), close: v.string() })),
    })),
    alwaysOpen: v.optional(v.boolean()),
    curatorChoice: v.boolean(),
    caption: v.string(),
    address: v.string(),
    updatedAt: v.number(),
    createdAt: v.number(),
  }).index("by_location_id", ["id"]),
});
